---
version: '3'
services:
  vin2cert:
#    image: vin2cert
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: vin2cert-app
    ports: ['8080:80']
    extra_hosts: 
     - "elasticsearch:${AWSIP}"
    logging:
      driver: gelf
      options:
        gelf-address: udp://${AWSIP}:12201
        tag: "vin2cert"

  websocket:
#    image: websocket
    build:
      context: ./websocket
      dockerfile: Dockerfile
    container_name: websocket-app
    ports: ['1337:1337']
    extra_hosts: 
     - "elasticsearch:${AWSIP}"
    logging:
      driver: gelf
      options:
        gelf-address: udp://${AWSIP}:12201
        tag: "websocket"

#  filebeat:
#    image: docker.elastic.co/beats/filebeat:${TAG}
#    container_name: vin2cert-filebeat
#    # If the host system has logs at "/var/log", mount them at "/mnt/log"
#    # inside the container, where Filebeat can find them.
#    volumes: ['/var/lib/docker/containers:/mnt/log:ro']

