---
version: '3'
services:
  vin2cert:
#    image: vin2cert
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: vin2cert-app
    ports: ['8080:80']
    extra_hosts: 
     - "elasticsearch:${AWSIP}"
     - "websocket:${AWSIP}"
    logging:
      driver: gelf
      options:
        gelf-address: udp://${AWSIP}:12201
        tag: "vin2cert"
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    depends_on: ['websocket']


  websocket:
#    image: websocket
    build:
      context: ./websocket
      dockerfile: Dockerfile
    container_name: websocket-app
    ports: ['1337:1337']
    extra_hosts: 
     - "elasticsearch:${AWSIP}"
    logging:
      driver: gelf
      options:
        gelf-address: udp://${AWSIP}:12201
        tag: "websocket"
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"


  demonstrator:
#    image: demonstrator
    build:
      context: ./demonstrator
      dockerfile: Dockerfile
    container_name: demonstrator-app
    ports: ['80:80']
    extra_hosts: 
     - "elasticsearch:${AWSIP}"
     - "websocket:${AWSIP}"
    environment:
     - APIURL="http://${AWSIP}:8080/api.php"
     - WSURL=${AWSIP}
     - WSPORT=1337
    logging:
      driver: gelf
      options:
        gelf-address: udp://${AWSIP}:12201
        tag: "demonstrator"
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    depends_on: ['websocket']


#  filebeat:
#    image: docker.elastic.co/beats/filebeat:${TAG}
#    container_name: vin2cert-filebeat
#    # If the host system has logs at "/var/log", mount them at "/mnt/log"
#    # inside the container, where Filebeat can find them.
#    volumes: ['/var/lib/docker/containers:/mnt/log:ro']

