---
version: '3'
services:
  vin2cert:
    image: patrickriegler/vin2cert_vin2cert
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: vin2cert-app
    ports: ['8080:80']
    volumes:
      - ./api:/var/www/html/vin2cert
    extra_hosts: 
     - "elasticsearch:${AWSIP}"
     - "websocket:${AWSIP}"
    environment:
     - WSURL=${AWSIP}
     - WSPORT=1337
    logging:
      driver: gelf
      options:
        gelf-address: udp://${AWSIP}:12201
        tag: "vin2cert"
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    depends_on: ['websocket']


  image2text:
    image: patrickriegler/vin2cert_image2text
    build:
      context: ./image2text
      dockerfile: Dockerfile
    container_name: image2text-app
    ports: ['8090:80']
    volumes:
      - ./image2text:/var/www/html/image2text
    extra_hosts: 
     - "elasticsearch:${AWSIP}"
     - "websocket:${AWSIP}"
    environment:
     - WSURL=${AWSIP}
     - WSPORT=1337
     - AWS_ACCESS_KEY_ID=AKIAICE4JY4RBPHKOXWQ
     - AWS_SECRET_ACCESS_KEY=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
    logging:
      driver: gelf
      options:
        gelf-address: udp://${AWSIP}:12201
        tag: "image2text"
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  websocket:
    image: patrickriegler/vin2cert_websocket
    build:
      context: ./websocket
      dockerfile: Dockerfile
    container_name: websocket-app
    ports: ['1337:1337']
#    volumes:
#      - ./websocket:/usr/src/websocket
    extra_hosts: 
     - "elasticsearch:${AWSIP}"
    logging:
      driver: gelf
      options:
        gelf-address: udp://${AWSIP}:12201
        tag: "websocket"
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"


  demonstrator:
    image: patrickriegler/vin2cert_demonstrator
    build:
      context: ./demonstrator
      dockerfile: Dockerfile
    container_name: demonstrator-app
    ports: ['80:80']
#    volumes:
#      - ./demonstrator/html:/var/www/html/demonstrator
    extra_hosts: 
     - "elasticsearch:${AWSIP}"
     - "websocket:${AWSIP}"
    environment:
     - APIURL="http://${AWSIP}:8080/vin2cert/vin2cert.php"
     - WSURL=${AWSIP}
     - WSPORT=1337
    logging:
      driver: gelf
      options:
        gelf-address: udp://${AWSIP}:12201
        tag: "demonstrator"
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    depends_on: ['websocket']


#  filebeat:
#    image: docker.elastic.co/beats/filebeat:${TAG}
#    container_name: vin2cert-filebeat
#    # If the host system has logs at "/var/log", mount them at "/mnt/log"
#    # inside the container, where Filebeat can find them.
#    volumes: ['/var/lib/docker/containers:/mnt/log:ro']

